#
# This file is part of switch.py. See the LICENSE and the COPYRIGHTS files for
# more information about the licensing of this file.
#

user: admin
password: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918  # SHA256 hash of the password to use.
language: fr  # Locale to use for the admin interface. Only en and fr are currently available.
switches:  # Defines here the switches you want to control.
  circulator:  # Defines the internal name of the switch.
    module: example_switch  # The name of the module in the switches package to use to effectively control the switch.
    name: Circulateur  # Sets the name to be used in the admin interface.
    levels: 1  # Sets the different levels of intensity available for this switch. Minimum is 1.